# Generated by Django 5.2.7 on 2025-11-07 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_announcement_teacher_alter_answer_teacher_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Super Admin', 'Super Admin'), ('School Admin', 'School Admin'), ('Teacher', 'Teacher'), ('Student', 'Student')], default='Student', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='courses.school'),
        ),
    ]
